{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{ezpagedata_set( 'extra_menu', false() )}
<div class="warning-404">
<h2>404: Siden ble ikke funnet</h2>
<p>Ooops! Siden du leter etter finnes ikke. Denne feilen har annsyligvis oppstått fordi du har tastret inn feil adresse, eller fordi du har fulgt en lenke som ikke fungerer. Dobbeltsjekk adressen og prøv på nytt, eller se om du finner det du leter etter med en av disse lenkene: </p>
<ul>
    <li><a href="/">Gå til forsiden</a></li>
    <li><a href="/content/view/sitemap/2">Gå til nettsidekart</a></li>
</ul>
<p>Gi oss gjerne tilbakemelding på linker som ikke fungerer</p>
<p><a href="mailto:furnes@furnes-hamjern.no">furnes@furnes-hamjern.no</a></p>
</div>
{if $embed_content}
	{$embed_content}
{/if}
